### ISSUE TITLE
Export slots for Time Signature Message

### ISSUE THREAD

**Issue by ldenman** [pcrama/midi#3]
Hi, thank you for this fork. I am new to common lisp.

I tried following the example in the usage/testmidi file in my own project (https://github.com/pcrama/midi/blob/master/usage/testmidi.lisp)
I was unable to get these to work from my project due to 'dd,'nn,'cc,'bb not being :EXPORTED in the midi package 

 (setf (slot-value (first timing-track) 'midi:dd) 2
          (slot-value (first timing-track) 'midi:nn) 4
          (slot-value (first timing-track) 'midi:cc) 24
          (slot-value (first timing-track) 'midi:bb) 8)

Shouldn't these symbols be exported? I had to clone the project and change the file locally.

Thanks for any advice

**Comment by pcrama** [comment]
Thank you for the issue & merge request!
